blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RepairYourTech/Symbiote/discussions/categories/feature-requests
      about: Share and vote on feature requests for Symbiote
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RepairYourTech.symbiote&ssr=false#review-details
      about: Enjoying Symbiote? Leave a review here!
